export const defaultHashtags = [
  { title: "#ShopOnline", year: 2024 },
  { title: "#OnlineShopping", year: 2024 },
  { title: "#ShopNow", year: 2024 },
  { title: "#EcommerceStore", year: 2024 },
  { title: "#OnlineBoutique", year: 2024 },
  { title: "#ShoppingOnline", year: 2024 },
  { title: "#BuyOnline", year: 2024 },
  { title: "#DigitalShopping", year: 2024 },
  { title: "#MustHave", year: 2024 },
  { title: "#NewArrivals", year: 2024 },
  { title: "#TrendingNow", year: 2024 },
  { title: "#ShopSmall", year: 2024 },
  { title: "#BestDeals", year: 2024 },
  { title: "#ShopLocal", year: 2024 },
  { title: "#DailyFinds", year: 2024 },
  { title: "#OnlineDeals", year: 2024 },
  { title: "#RetailTherapy", year: 2024 },
  { title: "#ShoppingTime", year: 2024 },
  { title: "#InstaShopping", year: 2024 },
  { title: "#ShopaholicLife", year: 2024 },
  { title: "#OnlineRetail", year: 2024 },
  { title: "#EasyShop", year: 2024 },
  { title: "#SmartShopping", year: 2024 },
  { title: "#ShoppingMood", year: 2024 },
  { title: "#CustomerLove", year: 2024 },
  { title: "#ShopWithUs", year: 2024 },
  { title: "#HappyShopping", year: 2024 },
  { title: "#CustomerChoice", year: 2024 },
  { title: "#ShopperStyle", year: 2024 },
  { title: "#ShoppingCommunity", year: 2024 },
  { title: "#ShopAndShare", year: 2024 },
  { title: "#SpecialOffer", year: 2024 },
  { title: "#Discount", year: 2024 },
  { title: "#SaleAlert", year: 2024 },
  { title: "#DealOfTheDay", year: 2024 },
  { title: "#ShopSale", year: 2024 },
  { title: "#OnlineSale", year: 2024 },
  { title: "#BestPrice", year: 2024 },
  { title: "#ShoppingDeals", year: 2024 },
  { title: "#EcommerceLife", year: 2024 },
];

export const CTAtitles = [
  { title: "Shop Now", value: "SHOP_NOW" },
  { title: "Buy Now", value: "BUY_NOW" },
  { title: "Order Now", value: "ORDER_NOW" },
];
